NOISSUE - Update UI port
ultravioletrs/cube-docs pull request #13
Opened 2024-11-27 13:28 UTC by JeffMboya

# What type of PR is this?
This is a documentation update

## What does this do?
Updates UI port from `3000` to `6193`

## Which issue(s) does this PR fix/relate to?
No issues

## Have you included tests for your changes?
No

## Did you document any new/modified features?
No

### Notes

2024-11-27 15:49 UTC, rodneyosodo requested changes

2024-11-27 15:49 UTC, rodneyosodo commented on docs/getting-started.md
> +      "apiBase": "http://<yourr-ollama-instance>/ollama"
```suggestion
      "apiBase": "http://<your-ollama-instance>/ollama"
```

same as others

2024-11-29 12:48 UTC, rodneyosodo requested changes
For the diagram, edit the one in the shared Google Drive folder.

2024-11-29 13:11 UTC, rodneyosodo approved these changes

2024-11-29 13:14 UTC, drasko approved these changes
LGTM

2024-11-29 13:14 UTC, merged